# Generated by Django 5.0 on 2024-03-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Businessowner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
