# Generated by Django 5.0 on 2024-03-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_tbl_warehouse_warehousereg_district'),
        ('Businessowner', '0002_delete_tbl_product'),
        ('Guestapp', '0010_tbl_ownerreg_ownerregistration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
                ('product_image', models.FileField(upload_to='ProductDoc/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_ownerreg')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_subtype')),
            ],
        ),
    ]
