# Generated by Django 5.0 on 2024-03-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Businessowner', '0003_tbl_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
