# Generated by Django 5.0 on 2024-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehousereg_name', models.CharField(max_length=50)),
                ('warehousereg_district', models.CharField(max_length=50)),
                ('warehousereg_address', models.CharField(max_length=50)),
                ('warehousereg_email', models.CharField(max_length=50)),
                ('warehousereg_password', models.CharField(max_length=50)),
            ],
        ),
    ]
