# Generated by Django 4.2.7 on 2024-03-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guestapp', '0010_tbl_ownerreg_ownerregistration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.CharField(default=0, max_length=10)),
                ('payment_status', models.CharField(default=0, max_length=10)),
                ('booking_totalamount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_userreg')),
            ],
        ),
    ]
