# Generated by Django 4.2.7 on 2024-03-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_totalamount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
