# Generated by Django 4.2.7 on 2024-03-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouseapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_deliveryboy',
        ),
    ]
