# Generated by Django 4.2.7 on 2024-03-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Warehouseapp', '0002_delete_tbl_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboy_name', models.CharField(max_length=50)),
                ('deliveryboy_email', models.CharField(max_length=50)),
                ('deliveryboy_contact', models.CharField(max_length=50)),
                ('deliveryboy_photo', models.FileField(upload_to='DeliveryBoyDocs/')),
                ('deliveryboy_password', models.CharField(max_length=50)),
                ('deliveryboy_address', models.CharField(max_length=50)),
            ],
        ),
    ]
