# Generated by Django 4.2.7 on 2024-03-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_tbl_warehouse_warehousereg_district'),
        ('Warehouseapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deliveryboy',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_warehouse'),
        ),
    ]
