# Generated by Django 4.2.7 on 2024-03-15 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_alter_tbl_booking_booking_totalamount'),
        ('Warehouseapp', '0004_tbl_deliveryboy_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigndelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_status', models.CharField(default=0, max_length=10)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.tbl_cart')),
                ('deliveryboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouseapp.tbl_deliveryboy')),
            ],
        ),
    ]
