# Generated by Django 4.2.7 on 2024-03-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_alter_tbl_booking_booking_totalamount'),
        ('Warehouseapp', '0005_assigndelivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assigndelivery',
            new_name='tbl_assigndelivery',
        ),
    ]
