# Generated by Django 5.0 on 2024-02-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ownerreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerregistration_name', models.CharField(max_length=50)),
                ('ownerregistration_about', models.CharField(max_length=50)),
                ('ownerregistration_contact', models.CharField(max_length=50)),
                ('ownerrregistration_email', models.CharField(max_length=50)),
                ('owerregistration_district', models.CharField(max_length=50)),
                ('ownerregistration_proof', models.FileField(upload_to='OwnerDoc/')),
                ('ownerregistration_photo', models.FileField(upload_to='OwnerDoc/')),
                ('ownerregistration_password', models.CharField(max_length=50)),
                ('ownerregistration_confirmpassword', models.CharField(max_length=50)),
                ('ownerregistration_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userregistration_name', models.CharField(max_length=50)),
                ('userregistration_contact', models.CharField(max_length=50)),
                ('userregistration_email', models.CharField(max_length=50)),
                ('userregistration_address', models.CharField(max_length=50)),
                ('userregistration_gender', models.CharField(max_length=50)),
                ('userregistration_photo', models.FileField(upload_to='UserDoc/')),
                ('userregistration_password', models.CharField(max_length=50)),
                ('userregistration_confirmpassword', models.CharField(max_length=50)),
                ('userregistration_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_place')),
            ],
        ),
    ]
