# Generated by Django 5.0 on 2024-02-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ownerreg',
        ),
    ]
