# Generated by Django 5.0 on 2024-02-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0002_delete_tbl_ownerreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userreg',
        ),
    ]
