# Generated by Django 5.0 on 2024-02-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_userreg',
            name='userregistration_place',
        ),
        migrations.DeleteModel(
            name='tbl_ownerreg',
        ),
        migrations.DeleteModel(
            name='tbl_userreg',
        ),
    ]
