# Generated by Django 5.0 on 2024-02-19 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0001_initial'),
        ('Guestapp', '0005_remove_tbl_userreg_userregistration_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ownerreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerregistration_name', models.CharField(max_length=50)),
                ('ownerregistration_about', models.CharField(max_length=50)),
                ('ownerregistration_contact', models.CharField(max_length=50)),
                ('ownerrregistration_email', models.CharField(max_length=50)),
                ('ownerregistration_address', models.CharField(max_length=50)),
                ('owerregistration_district', models.CharField(max_length=50)),
                ('ownerregistration_proof', models.FileField(upload_to='OwnerDoc/')),
                ('ownerregistration_photo', models.FileField(upload_to='OwnerDoc/')),
                ('ownerregistration_password', models.CharField(max_length=50)),
                ('ownerregistration_confirmpassword', models.CharField(max_length=50)),
                ('ownerregistration_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_place')),
            ],
        ),
    ]
