# Generated by Django 5.0 on 2024-02-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0007_tbl_userreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userreg',
        ),
    ]
