# Generated by Django 5.0 on 2024-02-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
        ('Guestapp', '0008_delete_tbl_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userregistration_name', models.CharField(max_length=50)),
                ('userregistration_contact', models.CharField(max_length=50)),
                ('userregistration_email', models.CharField(max_length=50)),
                ('userregistration_address', models.CharField(max_length=50)),
                ('userregistration_gender', models.CharField(max_length=50)),
                ('userregistration_photo', models.FileField(upload_to='UserDoc/')),
                ('userregistration_password', models.CharField(max_length=50)),
                ('userregistration_confirmpassword', models.CharField(max_length=50)),
                ('userregistration_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_place')),
            ],
        ),
    ]
